import {
  BookmarksIcon,
  BookmarksFillIcon,
  ExploreIcon,
  ExploreFillIcon,
  HomeIcon,
  HomeFillIcon,
  ListsIcon,
  ListsFillIcon,
  MessagesIcon,
  MessagesFillIcon,
  MoreIcon,
  NotificationsIcon,
  NotificationsFillIcon,
  ProfileIcon,
  ProfileFillIcon,
} from '../components/icons';

// export default {
//   TABLET_SIZE: 980,
//   DESKTOP_SIZE: 1270,
// };

export const MENU = [
  {
    key: 'home',
    path: '/',
    icon: HomeIcon,
    iconSelected: HomeFillIcon,
    title: 'Home',
    notify: 0,
  },
  {
    key: 'explore',
    path: '/explore',
    icon: ExploreIcon,
    iconSelected: ExploreFillIcon,
    title: 'Explore',
    notify: 0,
  },
  {
    key: 'notifications',
    path: '/notifications',
    icon: NotificationsIcon,
    iconSelected: NotificationsFillIcon,
    title: 'Notifications',
    notify: 17,
  },
  {
    key: 'messages',
    path: '/messages',
    icon: MessagesIcon,
    iconSelected: MessagesFillIcon,
    title: 'Messages',
    notify: 0,
  },
  {
    key: 'bookmarks',
    path: '/bookmarks',
    icon: BookmarksIcon,
    iconSelected: BookmarksFillIcon,
    title: 'Bookmarks',
    notify: 0,
  },
  {
    key: 'lists',
    path: '/lists',
    icon: ListsIcon,
    iconSelected: ListsFillIcon,
    title: 'Lists',
    notify: 0,
  },
  {
    key: 'profile',
    path: '/profile',
    icon: ProfileIcon,
    iconSelected: ProfileFillIcon,
    title: 'Profile',
    notify: 0,
  },
  {
    key: 'more',
    path: '/more',
    icon: MoreIcon,
    iconSelected: MoreIcon,
    title: 'More',
    notify: 0,
  },
];

export const trends = [
  {
    name: '#javascript',
    url: 'https://twitter.com/hashtag/javascript?src=hash',
    tweetCount: '1.2k',
    tweetCountText: 'tweets',
  },
  {
    name: '#reactjs',
    url: 'https://twitter.com/hashtag/reactjs?src=hash',
    tweetCount: '50.232',
    tweetCountText: 'tweets',
  },
  {
    name: '#reactnative',
    url: 'https://twitter.com/hashtag/reactnative?src=hash',
    tweetCount: '2.43k',
    tweetCountText: 'tweets',
  },
  {
    name: '#html',
    url: 'https://twitter.com/hashtag/html?src=hash',
    tweetCount: '2.2k',
    tweetCountText: 'tweets',
  },
  {
    name: '#javascript',
    url: 'https://twitter.com/hashtag/javascript?src=hash',
    tweetCount: '1.2k',
    tweetCountText: 'tweets',
  },
  {
    name: '#reactjs',
    url: 'https://twitter.com/hashtag/reactjs?src=hash',
    tweetCount: '50.232',
    tweetCountText: 'tweets',
  },
  {
    name: '#reactnative',
    url: 'https://twitter.com/hashtag/reactnative?src=hash',
    tweetCount: '2.43k',
    tweetCountText: 'tweets',
  },
  {
    name: '#html',
    url: 'https://twitter.com/hashtag/html?src=hash',
    tweetCount: '2.2k',
    tweetCountText: 'tweets',
  },
  {
    name: '#javascript',
    url: 'https://twitter.com/hashtag/javascript?src=hash',
    tweetCount: '1.2k',
    tweetCountText: 'tweets',
  },
  {
    name: '#reactjs',
    url: 'https://twitter.com/hashtag/reactjs?src=hash',
    tweetCount: '50.232',
    tweetCountText: 'tweets',
  },
];
